# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.hec.gov.pk/english/universities/Pages/recognised.aspx")
    self.driver.set_window_size(697, 720)
    self.driver.find_element(By.CSS_SELECTOR, "#ParentTobeAppend1 .read-more-arrow").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "http://www.abasyn.edu.pk").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-bar:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .readmore").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4) > .col-xs-12:nth-child(1)").click()
    self.vars["Program"] = self.driver.find_element(By.LINK_TEXT, "BS Political Science").text
  
