# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUniversity7():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_university7(self):
    self.driver.get("https://www.eduvision.edu.pk/programs-offered-in-agricultural-sciences-at-bachelor-level-in-pakistan")
    self.driver.set_window_size(1382, 736)
    element = self.driver.find_element(By.CSS_SELECTOR, ".sc_list > li:nth-child(2) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".home_category_news > .page-title").click()
    self.vars["ranks"] = self.driver.find_element(By.CSS_SELECTOR, ".sc_list > li:nth-child(1) > a").text
    self.vars["ranks"] = self.driver.find_element(By.CSS_SELECTOR, ".sc_list > li:nth-child(2) > a").text
    self.vars["ranks"] = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(18) > a").text
  
