# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSsss():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ssss(self):
    self.driver.get("https://www.hec.gov.pk/english/universities/Pages/recognised.aspx")
    self.driver.set_window_size(1382, 736)
    element = self.driver.find_element(By.LINK_TEXT, "Quality Assurance")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "ParentTobeAppend1").click()
    self.driver.find_element(By.LINK_TEXT, "http://www.abasyn.edu.pk").click()
    self.driver.find_element(By.LINK_TEXT, "Programs").click()
    self.driver.find_element(By.LINK_TEXT, "Undergraduate Programs (20)").click()
    self.vars["program1"] = self.driver.find_element(By.CSS_SELECTOR, "#collapse1 .title-cap:nth-child(1)").text
  
