# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUniversity2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_university2(self):
    self.driver.get("https://www.eduvision.edu.pk/programs-offered-in-engineering-at-bachelor-level-in-pakistan")
    self.driver.set_window_size(697, 720)
    self.driver.execute_script("window.scrollTo(0,692)")
    self.driver.find_element(By.NAME, "disciplineType").click()
    dropdown = self.driver.find_element(By.NAME, "disciplineType")
    dropdown.find_element(By.XPATH, "//option[. = 'Computer Sciences & Information Technology']").click()
    self.driver.find_element(By.NAME, "Submit").click()
    self.driver.execute_script("window.scrollTo(0,1546)")
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(5) .btn:nth-child(1)").click()
    self.driver.switch_to.frame(6)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "dismiss-button").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.default_content()
    self.driver.execute_script("window.scrollTo(0,581)")
    self.driver.execute_script("window.scrollTo(0,1248)")
  
