# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUniversity():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_university(self):
    self.driver.get("https://www.eduvision.edu.pk/programs-offered-in-engineering-at-bachelor-level-in-pakistan")
    self.driver.set_window_size(1382, 736)
    self.driver.execute_script("window.scrollTo(0,127)")
    self.driver.execute_script("window.scrollTo(0,850)")
    self.driver.execute_script("window.scrollTo(0,987)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .btn:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,537)")
  
